name: Spring Boot CI/CD
run-name: Spring Boot CI/CD run

on:
  push:
    branches:
      - master   # Thay đổi nếu nhánh chính của cậu khác
  pull_request:
    branches:
      - master   # Thay đổi nếu nhánh chính của cậu khác

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Vietnamnet.vn
          MYSQL_DATABASE: autolabel_issue
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=3

    steps:
    # Bước 1: Lấy mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Bước 2: Cài đặt Java JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    # Bước 3: Chờ MySQL service khởi động (sleep 30 giây)
    - name: Sleep for MySQL to be ready in 30 seconds
      run: sleep 30

    # Bước 4: Build dự án (chạy clean install, skip test)
    - name: Build with Maven (CI profile)
      run: mvn clean install -Dspring.profiles.active=ci -DskipTests

    # Bước 5: Chạy test (nếu có)
    - name: Run tests
      run: mvn test -Dspring.profiles.active=ci

    # Bước 6: Đóng gói project (mvn package)
    - name: Package application
      run: mvn package
