name: Spring Boot CI/CD
run-name: Spring Boot CI/CD run name 
on:
  push:
    branches:
      - master  # Thay thế 'main' bằng tên nhánh của bạn nếu khác
  pull_request:
    branches:
      - master  # Thay thế 'main' nếu cần

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Cài đặt dịch vụ mysql:latest docker
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Vietnamnet.vn
          MYSQL_DATABASE: autolabel_issue
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=3
    
    steps:
    # Bước 1: Checkout mã nguồn từ repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Bước 2: Cài đặt Java JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'  # Chọn JDK distribution phù hợp với JDK 21

    # Bước 3: Cài đặt dependencies và build dự án bằng Maven
    - name: Build with Maven (CI profile)
      run: mvn clean install -Dspring.profiles.active=ci -DskipTests
    
    - name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -hmysql -uroot -pVietnamnet.vn --silent; then
            echo "MySQL is ready!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done

    # Bước 4: Chạy các bài test (nếu có)
    - name: Run tests
      run: mvn test
      
    # Bước 5: Đóng gói và chuẩn bị artifact (nếu cần)
    - name: Package application
      run: mvn package